### ISSUE TITLE
Can you show me how to run on Windows?

### ISSUE THREAD

**Issue by bao-O** [twmht/python-seetaface2#3]
I tried to run your API on Windows as the instruction. After copying lib folder into your folder project, I run the command: `python setup.py install` but this error occured:
![2019-12-02](https://user-images.githubusercontent.com/44353216/69923380-f7225280-14d6-11ea-8e0a-32d168576500.png)
What did I miss? And if can, can you show me how to install more clearly? Thank in advance!

**Comment by twmht** [comment]
you should try `git clone --recursive`
